[build]
  publish = "."

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/applicants"
  to = "/.netlify/functions/applicants"
  status = 200
